from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # path('', views.home, name="home"),
    path('account/login/', views.loginUser, name="login"),
    path('account/logout/', views.logoutUser, name="logout"),
    path('account/register/', views.registerUser, name="register"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('account/verification/', views.verification, name="verification"),
    path('account/verified/', views.verified, name="verified"),
    path('about/', views.about, name="aboutus"),
    path('contact/', views.contact, name="contact"),
    # path('tracker/', views.tracker, name="racker"),
    path('search/', views.search, name="search"),
    path('product-view/<slug:slug>/', views.productView, name="product_view"),
    path('cart-product-view/<slug:slug>/<int:cid>/', views.cart_prod_view,
         name="cart_product_view"),
    path('add-to-cart/<str:rw>/<str:ds>/<int:pid>/', views.add_to_cart, name="add_to_cart"),
    path('cart/', views.cart, name="cart"),
    path('cart_update/<str:rw>/<str:ds>/<str:dd>/<str:rd>/<int:pid>/<int:cid>/', views.cart_update,
         name="cart_update"),
    path('cart_delete/<int:cid>/', views.cart_delete, name="cart_delete"),
    # path('checkout/', views.checkout, name="checkout"),
    path('account/reset_password/',
         auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),
         name="reset_password"),
    path('account/reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_sent.html"),
         name="password_reset_done"),
    path('account/reset_/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_form.html"),
         name="password_reset_confirm"),
    path('account/reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"),
         name="password_reset_complete"),
    path('cart_count/', views.cart_count, name="cart_count"),
    path('ratings/', views.rating, name="rating"),
    path('review-rate/', views.review_rate, name="review_rate"),
    path('rating-refuse/', views.rating_refuse, name="rating_refuse"),
    path('query/<int:pid>/', views.query, name="query"),
    path('question/<int:pid>/', views.queryPage, name="question"),
    path('proceed-rent/', views.proceed_rent, name="proceed_rent"),
    path('verification-code/', views.verify_code, name="verify_code"),
    path('proceed-pay/', views.proceed_pay, name="proceed_pay"),
    path('payment/', views.payment, name="payment"),
    path('proceed-pay/paid-esewa/', views.paid_esewa, name="paid_esewa"),
    path('proceed-pay/paid-khalti/', views.paid_khalti, name="paid_khalti"),
    path('proceed-pay/success-esewa-pay?q=su/<str:oid>/<str:amt>/<str:refid>/', views.success_esewa_pay, name="success_esewa_pay"),
    path('proceed-pay/fail-esewa-pay?q=su/', views.fail_esewa_pay, name="fail_esewa_pay"),
    path('user_detail/', views.user_detail, name="user_detail"),
    path('user_update_shipping/', views.user_update_shipping, name="user_update_shipping"),
    path('confirm-order/', views.confirm_order, name="confirm_order"),
    path('order_update/', views.order_update, name="order_update"),
    path('order_credit_update/', views.order_credit_update, name="order_credit_update"),
    path('account/manage-account/personal-detail/', views.manage_account_personal, name="manage_account_personal"),
    path('account/manage-account/update-personal-info/', views.account_personal_edit, name="personal_edit"),
    path('account/manage-account/personal-update/', views.personal_update, name="personal_update"),
    path('account/manage-account/shipping-detail/', views.manage_account_shipping, name="manage_account_shipping"),
    path('account/manage-account/update-shipping-info/', views.account_shipping_edit, name="shipping_edit"),
    path('account/manage-account/shipping-update/', views.shipping_update, name="shipping_update"),
    path('account/my-orders/', views.my_order, name="my_order"),
    path('account/my-wishlist/', views.my_wishlist, name="my_wishlist"),
    path('add_to_wishlist/<int:pid>/', views.add_to_wishlist, name="add_to_wishlist"),
    path('delete_wishlist/<int:wid>/', views.delete_wishlist, name="delete_wishlist"),
    path('account/notifications/', views.notifications, name="notifications"),
    path('account/cancel/<int:pid>/<int:on>/<str:ps>/<int:qty>/', views.cancel, name="cancel"),
    path('account/my-cancellations/', views.my_cancellations, name="my_cancellations"),
    path('products/', views.products_display, name="products"),
    path('rent_dress/', views.rent_dress, name="rent_dress"),
    path('filter_product/<str:fp>/', views.filter_product, name="filter_prod"),
    path('filter_product_gender/<str:fg>/<str:fp>/', views.filter_product_gender, name="filter_product_gender"),
    path('filter_product_tradition/<str:ft>/<str:fg>/<str:fp>/', views.filter_product_tradition,
         name="filter_product_tradition"),

]
