# Generated by Django 3.0.5 on 2020-06-14 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_dress_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=100)),
                ('caste_type', models.CharField(default='', max_length=100)),
                ('dress_type', models.CharField(default='', max_length=100)),
                ('renting_way', models.CharField(max_length=20)),
                ('product_size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('refund', models.IntegerField(default=0)),
                ('renting_days', models.CharField(max_length=50)),
                ('delivery_date', models.CharField(max_length=50)),
                ('returning_date', models.CharField(max_length=50)),
                ('image', models.CharField(default='', max_length=100)),
                ('added_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(default='', help_text='write in lowercase', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DressColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', help_text='write in lowercase', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress', models.CharField(default='', help_text='write in lowercase', max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('----', '----'), ('men', 'men'), ('women', 'women')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('total_items', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('order_status_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('order_number', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
                ('customer_user_name', models.CharField(default='', max_length=100)),
                ('customer_email', models.CharField(default='', max_length=200)),
                ('customer_contact', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('caste_type', models.CharField(max_length=100)),
                ('dress_type', models.CharField(max_length=100)),
                ('renting_way', models.CharField(max_length=20)),
                ('product_size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('refund', models.IntegerField(default=0)),
                ('renting_days', models.CharField(max_length=50)),
                ('delivery_date', models.CharField(max_length=50)),
                ('returning_date', models.CharField(max_length=50)),
                ('shipping_address', models.CharField(max_length=2038)),
                ('shipping_charge', models.IntegerField()),
                ('prod_image', models.ImageField(upload_to='img')),
                ('ordered_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('payment_status', models.CharField(default='Cash On Delivery', max_length=100)),
                ('order_status', models.CharField(choices=[('Rental Reserved', 'Rental Reserved'), ('Rental Returned', 'Rental Returned')], default='Rental Reserved', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_full_name', models.CharField(default='', max_length=200)),
                ('user_email', models.CharField(default='', max_length=255)),
                ('user_contact', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('sub_total_amount', models.IntegerField()),
                ('total_refund', models.IntegerField()),
                ('shipping_charge', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('delivery_date', models.CharField(max_length=50)),
                ('shipping_address', models.CharField(default='', max_length=2038)),
                ('payment_status', models.CharField(default='Cash On Delivery', max_length=100)),
                ('ordered_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Processing', help_text='Change order status date and time when you change order status', max_length=50)),
                ('order_status_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.CharField(default='', help_text='write in lowercase', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('question', models.CharField(max_length=2038)),
                ('answer', models.CharField(max_length=2038)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Bhaktapur', 'Bhaktapur'), ('Kathmandu Metro 10 - New Baneshwor Area', 'Kathmandu Metro 10 - New Baneshwor Area'), ('Kathmandu Metro 11 - Maitighar Area', 'Kathmandu Metro 11 - Maitighar Area'), ('Kathmandu Metro 12 - Teku Area', 'Kathmandu Metro 12 - Teku Area'), ('Kathmandu Metro 13 - Kalimati Area', 'Kathmandu Metro 13 - Kalimati Area'), ('Kathmandu Metro 14 - Kuleshwor Area', 'Kathmandu Metro 14 - Kuleshwor Area'), ('Kathmandu Metro 15 - Swayambhu Area', 'Kathmandu Metro 15 - Swayambhu Area'), ('Kathmandu Metro 16 - Nayabazar Area', 'Kathmandu Metro 16 - Nayabazar Area'), ('Kathmandu Metro 17 - Chhetrapati Area', 'Kathmandu Metro 17 - Chhetrapati Area'), ('Kathmandu Metro 18 - Raktakali Area', 'Kathmandu Metro 18 - Raktakali Area'), ('Kathmandu Metro 19 - Hanumandhoka Area', 'Kathmandu Metro 19 - Hanumandhoka Area'), ('Kathmandu Metro 1 - Naxal Area', 'Kathmandu Metro 1 - Naxal Area'), ('Kathmandu Metro 20 - Marutol Area', 'Kathmandu Metro 20 - Marutol Area'), ('Kathmandu Metro 21 - Lagantol Area', 'Kathmandu Metro 21 - Lagantol Area'), ('Kathmandu Metro 22 - Newroad Area', 'Kathmandu Metro 22 - Newroad Area'), ('Kathmandu Metro 23 - Basantapur Area', 'Kathmandu Metro 23 - Basantapur Area'), ('Kathmandu Metro 24 - Indrachowk Area', 'Kathmandu Metro 24 - Indrachowk Area'), ('Kathmandu Metro 25 - Ason Area', 'Kathmandu Metro 25 - Ason Area'), ('Kathmandu Metro 26 - Lainchor Area', 'Kathmandu Metro 26 - Lainchor Area'), ('Kathmandu Metro 27 - Bhotahiti Area', 'Kathmandu Metro 27 - Bhotahiti Area'), ('Kathmandu Metro 28 - Bagbazar Area', 'Kathmandu Metro 28 - Bagbazar Area'), ('Kathmandu Metro 28 - Kamaladi Area', 'Kathmandu Metro 28 - Kamaladi Area'), ('Kathmandu Metro 29 - Anamnagar Area', 'Kathmandu Metro 29 - Anamnagar Area'), ('Kathmandu Metro 29 - Putalisadak Area', 'Kathmandu Metro 29 - Putalisadak Area'), ('Kathmandu Metro 2 - Lazimpat Area', 'Kathmandu Metro 2 - Lazimpat Area'), ('Kathmandu Metro 30 - Maitidevi Area', 'Kathmandu Metro 30 - Maitidevi Area'), ('Kathmandu Metro 31 - Min Bhavan Area', 'Kathmandu Metro 31 - Min Bhavan Area'), ('Kathmandu Metro 32 - Koteshwor Area', 'Kathmandu Metro 32 - Koteshwor Area'), ('Kathmandu Metro 32 - Tinkune Area', 'Kathmandu Metro 32 - Tinkune Area'), ('Kathmandu Metro 3 - Baluwatar Area', 'Kathmandu Metro 3 - Baluwatar Area'), ('Kathmandu Metro 3 - Maharajganj Area', 'Kathmandu Metro 3 - Maharajganj Area'), ('Kathmandu Metro 4 - Bishalnagar Area', 'Kathmandu Metro 4 - Bishalnagar Area'), ('Kathmandu Metro 5 - Tangal Area', 'Kathmandu Metro 5 - Tangal Area'), ('Kathmandu Metro 7 - Chabahil Area', 'Kathmandu Metro 7 - Chabahil Area'), ('Kathmandu Metro 8 - Gausala Area', 'Kathmandu Metro 8 - Gausala Area'), ('Kathmandu Metro 9 - Sinamangal Area', 'Kathmandu Metro 9 - Sinamangal Area'), ('Kathmandu Outside Ring Road', 'Kathmandu Outside Ring Road'), ('Lalitpur Inside Ring Road', 'Lalitpur Inside Ring Road'), ('Lalitpur Outside Ring Road', 'Lalitpur Outside Ring Road')], max_length=100)),
                ('shipping_charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=50)),
                ('contact', models.IntegerField(default='')),
                ('shipping_city', models.CharField(default='', max_length=50)),
                ('shipping_area', models.CharField(default='', max_length=50)),
                ('shipping_address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=100)),
                ('caste_type', models.CharField(default='', max_length=100)),
                ('dress_type', models.CharField(default='', max_length=100)),
                ('renting_way', models.CharField(max_length=20)),
                ('product_size', models.CharField(max_length=20)),
                ('image', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', unique=True)),
                ('person_category', models.CharField(choices=[('men', 'men'), ('women', 'women')], default='', help_text='Choose the gender the product belongs to', max_length=50)),
                ('element_category', models.CharField(choices=[('dress', 'dress')], default='', help_text='Choose the Element', max_length=50)),
                ('rent_price', models.IntegerField(default=0)),
                ('refund_amount', models.IntegerField(default=0)),
                ('stock_size_s', models.IntegerField(default=0, help_text='Enter stock of product with size "S"')),
                ('stock_size_m', models.IntegerField(default=0, help_text='Enter stock of product with size "M"')),
                ('stock_size_l', models.IntegerField(default=0, help_text='Enter stock of product with size "L"')),
                ('stock_size_xl', models.IntegerField(default=0, help_text='Enter stock of product with size "XL"')),
                ('stock_size_xxl', models.IntegerField(default=0, help_text='Enter stock of product with size "XXL"')),
                ('stock_size_3xl', models.IntegerField(default=0, help_text='Enter stock of product with size "3XL"')),
                ('product_details', models.CharField(default='', help_text='Enter products details like available color, size, ect', max_length=500)),
                ('pub_date', models.DateField()),
                ('main_image', models.ImageField(default='', help_text='Choose image to display as main display image of product', upload_to='img/prod_img')),
                ('sub_image1', models.ImageField(default='', help_text='Choose other image for the product', upload_to='img/prod_img')),
                ('sub_image2', models.ImageField(default='', help_text='Choose other image for the product', upload_to='img/prod_img')),
                ('caste_category', models.ForeignKey(blank=True, default='', help_text='Choose the caste type for product, if any else leave blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Caste', to='shop.Caste', to_field='caste')),
                ('designer', models.ForeignKey(blank=True, default='', help_text='Choose the designer for the product, if any else leave blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_designer', to='shop.ProductDesigner', to_field='designer')),
                ('dress_color', models.ForeignKey(blank=True, default='', help_text='Choose the color or add the color of the product, leave blank if the dress is traditional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dress_color', to='shop.DressColor', to_field='color')),
                ('dress_type', models.ForeignKey(blank=True, default='', help_text='Choose the dress_type for the product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dress_type', to='shop.Dresse', to_field='dress')),
                ('size', models.ManyToManyField(help_text='Choose sizes available for the product', to='shop.ProductSize')),
            ],
        ),
    ]
