# Generated by Django 3.0.5 on 2020-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='designer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
