# Generated by Django 3.0.5 on 2020-06-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='designer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='designer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
