# Generated by Django 3.0.5 on 2020-06-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200615_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='product_link',
            field=models.CharField(default='', max_length=2038),
        ),
    ]
