# Generated by Django 3.0.8 on 2020-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='verification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
