# Generated by Django 3.0.8 on 2020-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_userdetail_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='review_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
