# Generated by Django 3.0.8 on 2020-09-25 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
