# Generated by Django 3.0.8 on 2020-10-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200925_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
