# Generated by Django 3.0.8 on 2020-10-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201004_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
