# Generated by Django 3.0.8 on 2020-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201004_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='check_status',
            field=models.CharField(default='not checked', max_length=100),
        ),
        migrations.AddField(
            model_name='productquery',
            name='check_status',
            field=models.CharField(default='not checked', max_length=100),
        ),
        migrations.AddField(
            model_name='rating',
            name='check_status',
            field=models.CharField(default='not checked', max_length=100),
        ),
    ]
