# Generated by Django 3.0.8 on 2020-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orderdetail_order_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquery',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='img'),
        ),
    ]
