# Generated by Django 3.0.8 on 2020-10-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201006_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquery',
            name='answer',
            field=models.CharField(max_length=2038, null=True),
        ),
    ]
