# Generated by Django 3.0.8 on 2020-10-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201008_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquery',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=2038, null=True),
        ),
    ]
