# Generated by Django 3.0.8 on 2020-10-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201008_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquery',
            name='answer',
            field=models.CharField(default='', max_length=2038),
        ),
    ]
