# Generated by Django 3.0.8 on 2020-10-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201008_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquery',
            name='check_status',
        ),
    ]
