# Generated by Django 3.0.8 on 2020-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_productquery_check_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_text', models.CharField(max_length=255)),
                ('event_image', models.ImageField(upload_to='event')),
                ('event_days', models.IntegerField()),
                ('event_status', models.CharField(max_length=100)),
                ('event_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
