# Generated by Django 3.0.8 on 2020-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='img/event'),
        ),
    ]
